MAX_SCORE=100
MIN_SCORE=0
INITIAL_SOCRE=10
REDIS_HOST='localhost'
REDIS_PORT=6379
REDIS_PASSWORD=None
REDIS_KEY='proxies'


TARGET_URL = 'http://www.xicidaili.com/nn/'

POOL_UPPER_THRESHOLD=10000


VALID_STATUS_CODES=[200]
TEST_URL='http://baidu.com'
BATCH_TEST_SIZE=100


TESTER_CYCLE=20
GETTER_CYCLE=20
TESTER_ENABLED=True
GETTER_ENABLED=True
API_ENABLED=True
API_HOST='127.0.0.1'
API_PORT=8080
